### ISSUE TITLE
Feature request: API endpoint to get course info by ID

### ISSUE THREAD

**Issue by qu8n** [MyMCIT/MyMCIT#39]
Hi team,

Would we be able to have an API from MyMCIT that returns the following course info given a course ID?
- number of reviews
- average difficulty rating
- average workload
- average rating
- most recent review

I run PennPlanner.com and this would let me update the courses' ratings dynamically.

By the way, would it be ok if I start directing users/linking from PennPlanner to your app instead of MCITCentral?

Again, awesome work on this app!

(Edit: it doesn't look like I can edit this issue's label myself)

**Comment by chaoticgoodpanda** [comment]
Hi @qu8n , PennPlanner.com looks great!

We could do this, but I think we need to work out some sensible policies around this. I mean look, I don't think it's gonna get bombed with requests, but it's still useful to know:

- What's your requests per second needs
- Would you prefer a webhook setup, i.e. when a course review is added, new course is added, you get that new data from us, rather than you periodically calling our API and hoping for the best. It's a separate workstream, but building webhooks could be fun. :)

I'll sync with the team as to whether it should be a public API or we issue an API key. Will revert back.

Imo, it would be okay to start linking from PennPlanner to mymcit.org instead of MCITCentral, but @krisstern @drkchn have final say on that.

**Comment by qu8n** [comment]
@chaoticgoodpanda Thanks for responding so quickly.
> What's your requests per second needs

I don't expect to make a high amount of request volume to your server. The specific volume will depend on how we implement this, but for context, PennPlanner has ~10-15 daily active users. Whatever we do will probably be within the Vercel Hobby (free) plan's limits.

> Would you prefer a webhook setup

Webhook sounds fun. I'm also happy with a traditional API, too. If we go with the latter and you're worried about request volume, I could make requests only when user begins a new session and cache that data (I don't think there are new reviews that often). Overall, I'm flexible! Please keep me posted on what you all end up deciding.

**Comment by krisstern** [comment]
I would prefer using webhooks for this purpose as opposed to a traditional API as well.

**Comment by qu8n** [comment]
Update: closing this issue as this feature is no longer needed. I'm going to archive PennPlanner this fall in lieu of Penn adopting an enterprise solution. 🙌 (source: Jordan from the advising team)
